version: "2.2"
services:
  jobmanager:
    image: my-flink-app:latest
    ports:
      - "8081:8081"
    container_name: jobmanager  
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    # network_mode: host 
 
  taskmanager:
    image: my-flink-app:latest
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2 
    # network_mode: host
    container_name: taskmanager
